# Generated by Django 5.2.1 on 2025-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('RAP', 'Rap'), ('JAZZ', 'Jazz'), ('SAMBA', 'Samba'), ('PAGODE', 'Pagode'), ('CLASSICAL', 'Classical'), ('COUNTRY', 'Country'), ('IND', 'Indie'), ('REGGAE', 'Reggae'), ('BLUES', 'Blues'), ('FOLK', 'Folk'), ('ELECTRONIC', 'Electronic'), ('HIP_HOP', 'Hip Hop'), ('RNB', 'R&B'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('SKA', 'Ska'), ('FUNK', 'Funk'), ('SOUL', 'Soul'), ('DISCO', 'Disco'), ('GOSPEL', 'Gospel'), ('LATIN', 'Latin'), ('WORLD', 'World Music')], default='POP', max_length=20),
        ),
    ]
