# Generated by Django 5.2.1 on 2025-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_alter_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist_photos/'),
        ),
    ]
