# Generated by Django 5.2.1 on 2025-05-21 11:29

import festival.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=festival.models.artist_photo_path),
        ),
    ]
